apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealed-secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - n8n-pvc.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingress.yaml
