apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  accounts.tlarbals824: apiKey, login
  accounts.tlarbals824.enabled: "true"
  extension.config: |
    extensions:
      - name: argo-rollouts
        backend:
          services:
            - url: http://infra-argo-rollouts-dashboard.argo-rollouts:3100/api/v1
  url: https://argocd.simproject.kr
  dex.config: |
    connectors:
      - type: oidc
        id: cloudflare-access
        name: Cloudflare Access
        config:
          issuer: https://throbbing-voice-6c89.cloudflareaccess.com
          clientID: $argocd-cloudflare-access:clientID
          clientSecret: $argocd-cloudflare-access:clientSecret
          insecureEnableGroups: true
          insecureSkipEmailVerified: true
          scopes:
            - openid
            - profile
            - email
