---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-cloudflare-access
  namespace: argocd
spec:
  encryptedData:
    clientID: AgBydyFhzoym/NIoBtsOPWBCqrkRTBuyoPEYvdTtOn4gpcrSElSyAtnblYU4agCAt1SGbADnWygXkmq0P1zGZMKuyFMzKdM2s9vr2CUQf8sP7xSqDRIsV6BZlcY6520Svvbc8+tZz078Y0q45ObV1xXYNsx2LBGW6RTMJznpCeIlypHPg+IHhXEGiKUW4GsJ8Bzo4kk92ozkosUrk85lcDzz7InwJ+1iEAob90emiLofc0bXraJrjxr1+Syp3kFV84I7rdQd1R//YAwuBIQLu8slbG1SbKQBR266a6PapeIaYnB3/x19gkD26o47kf39pSCiuWoOne7GPuNYbvNoE/9alFPLhXAgbb3JljAiAJc+NhUmvA6//rcRuGib1urx+t7D+5Nuk/J1g9elvHG3GXQUIft60CdCHyBbghSRgWuQQtXCq+4xbt43QDszosYiSqV7t9odhSOamyqhRbwfpWUeUWni5+9UlNauoW66sqpeoN/n+ZZws4uXfQ5Cr9APfSkehCWLfPY41AMYLK+lOOuo1CTwR4ocGbwrrUcqFVAWxAMNOsmtsIs50R555mQyBDydOi9M+LP26yVgURJEN0PM23jL2zpA4UFE4U6CYxeVO/NN50ZFmYvnVk8WfXQDbQPnoyM+EIFjSVpS9BUBaMkxxOmBDCTseP3nSQW4Bs1OYteAETd67Vh0kTGMq/12+9WoOkOViKiPy+gtUEupsPt2aMirWOVoSM0sH8g9lA4S4sQ1+tCT/oE=
    clientSecret: AgCYStJNdTGFfwTMHwqsoHY+178eCW6XTQq10czv0/LmFmkAUx0Gi97oPWTQrtkHYiYaFWRT3n4eL1eY1GlNvZU6ITpF+liVdMV4enXvIEwKuxwBDWplpA60t3e8XtmQGPBk0eLrfIuhVM97ETgLYLY/valbUTKknEaUEJ/8rCSbrZyzk2C5hl1PTPcQYNuUxUevIdgJBTBZMpuJVK26QYXKckfncE/1gKe0/V0kfHXhYTEeH/aogAeqU2yS7jFocjEIvL+jwX5YYqKd/ox7Vvb0doCSbhbZIveJ9m/SVHvq3zhtNHvSDr2uw/wmbnMbfLBlA6x3XiG2/hbsDagFdxsVGOQQcBOzPHZKcPZVUQ5emOYsX2JURl62qYw2Ov7xXlpEt+a+BYbi1IeEAAWEP1JwF/Hk01X2tShwKQvPL/8kKyXXGZtDXZf4OET9pvtSukH6pd4iirU34ElTtVJONgCtSAouOq8/5fW98unYI/jk3wJHkwnGKMez0gfjqx2tQEDHtG6rg2cLEwQiZtKTrNemGq8gHOuO9OAftxE2Ev8uIvwM0kElepHO/3YZInzlbrJ8UIF7kpy7diQOaug/MI0keaNYDzoatHpMxZ2Ww8vUg+JZ96YEWp/FxjSEEOzS6Iox9yELYLm1SmTewEgPxPC/LquT4ZvQofx549uHBeEzj6yEwr6zDp2y3QLm+5UzbW0kgkvCcj66YLlzDTt8QfjJnrBK2ulpSOuRHhFkzpSgJYDVGIGL+lvrcl72rSywfWwB6+mQ0JTC/tyvk6b22gNp
  template:
    metadata:
      name: argocd-cloudflare-access
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
