apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nuclio-tls
  namespace: nuclio
spec:
  secretName: nuclio-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - serverless.simproject.kr
