apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  parentRefs:
    - name: public
      namespace: edge
      sectionName: https-argocd
  hostnames:
    - argocd.simproject.kr
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: bouncer
      backendRefs:
        - name: argocd-server
          port: 80
