---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: edge
spec:
  encryptedData:
    BOUNCER_KEY: AgChdtWBGGjz1PkXxDofcq1PeZ9jmjFVi2E09XsVIC7Mdt4AAhdn0wN0hfVVjxtJbEOIAXdMEiaVdS4dY94hPFereT4niK88Ew+mmcDzZsKSbcCPlHwRYMq4c5U+3VmZYU3053qwljf1y0mqDtdm7BzLHXTQSRiZpZnbrNsMF+9qHXdxdqMI6a1YKJmPaoKDiOaVaBXmGkSd4wNkTnneIt9NX1A044xqfpIglEttSbdlGhlPjhWGaNXirtHDCpEZWXgO4L9Qsfscu/ekzPwizfjN/POxFyW2eTn9BmX8rGTsluBZT0qIAW0WWfxlFV0SS2wrsLKf+hGicdAt/AxpVGQgI4j+IEXoUmryMe5yj27BSwWaXqoNOY9LR5ET8oqb4FKcJi213DvSctcDH0RcJ3olefv/3ypCJzyzB0RXL48TsPitGr1W2lw4WQux8rprB2aAlgrStSbsKval4sTCDl5s7XwQntE8VzUV8qTDn8NPrmp2yTXgvlHJfduj5BCSPVzDkj1IvSxv/esX88dSnVM5a52mWMI0lA0gwzPRRmJ2dncwyERrHPfgKx8b3ccx1EZvsUyy37CjwDoPpEKB/rVHAaDGW1Ia91dUkLIBdbLvwpXTS2DpU9CqjNmGzHLzeSMEceMh/TeyXja2D9EsDgSmV9qct2rKCbgWM1p95nzY8JeJyrZ93mWJ0in9B/Nrc7NCTQoiQzpHGCWZ3Vp5Gu1fMtUWjC3kmtN9uVxFBiHChkP25nJwuS8TQtTQ
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: edge
    type: Opaque
