---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    BOUNCER_KEY: AgCFC/ybRsIPZkilNlXLiAbqv1QBIoySF0Cf6gF+5cWTJmUP78n4PFrKvS7mt0QJ7rd4RLYP+riLrnfLPsbip5X2igGqHD/PzidAMcnKhbD7Q4RxrzSeK5QqJHp+HE8kKQKEvUwSHVcFeF9NBdidcj4jQYmOO5lMmirBZ4pGJezqtTj44WALUwxV2JR9iVA+IAj3byLWkhDVsc/39sDTsIBv4uUQuQQhdObXoK+h47RU94PMkvHOHq3KBfgFdECcFkcdBV22tASvqA44CSkmcJibuJriWQnfOmV/IHCFEWHmMO9tjFwjOaF84+8KOesZzTNbnju0tt35BqIgkXK6PzAVYiJxMqMIYoHjRUDFpYlVbqMIcn/4e9M5eTSTOpeIq/6U2TRE4esiKe1HbawcnTm2XH6ljy3beJNQ8AG9Kd0MG3qa8KXeuR5nXwOXbfABTPt4ps4RfT84A97U97M1foxQa3E/O6ibtRXtNetafEFRpT+sODRfiW3ZQhYgTsbtnu70FhDQpx8wGpl0IOJQvZqHaNVyHs04FDp4Bx2F2TUrMe+AwoDZxcb1VW1gZu4Hw2LoNey3Set/O27isEkHe75isum8V3sLSg7jPHyLbiOEQ5YczIjIxQbtD1SoPjPbu2paLXwMdyvVlYfYgT5kZdSjIqn1rEmBg70/pVXlPWTKjaGtDQOtky11nLyyM+Q+kt+hfAtJ0WosCwcLeKXfnaROsKQg9PZbcvuSib7EboLKU4uOLbmfOg8cvLHM
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
